# Generated by Django 3.1.2 on 2020-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_auto_20201118_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dept',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
